{% set name = "e3nn" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/e3nn-{{ version }}.tar.gz
  sha256: 5c2b414e9527aad27d755ae9546596e3f7706f45a21dae71c7deedb6c048e4de

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - opt_einsum_fx >=0.1.4
    - python >={{ python_min }}
    - scipy
    - sympy
    - pytorch >=1.8.0

test:
  imports:
    - e3nn
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://e3nn.org
  summary: Equivariant convolutional neural networks for the group E(3) of 3 dimensional rotations, translations, and mirrors.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
