schema_version: 1

context:
  name: e3nn
  version: "0.6.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/e3nn-${{ version }}.tar.gz
  sha256: 5c2b414e9527aad27d755ae9546596e3f7706f45a21dae71c7deedb6c048e4de

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - opt_einsum_fx >=0.1.4
    - python >=${{ python_min }}
    - scipy
    - sympy
    - pytorch >=1.8.0

tests:
  - python:
      imports:
        - e3nn
      pip_check: true
      python_version: ${{ python_min }}

about:
  summary: Equivariant convolutional neural networks for the group E(3) of 3 dimensional rotations, translations, and mirrors.
  license: MIT
  license_file: LICENSE
  homepage: https://e3nn.org

extra:
  recipe-maintainers:
    - jan-janssen
